[workspace]
resolver = "3"
members = [
    "crates/mochi-core",
    "crates/mochi-client",
    "crates/mochi-hotkey",
    "crates/mochi",
    "crates/mochic",
    "crates/mochi-testbed",
    "crates/mochi-render",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.96"
authors = ["Dominik Könitzer"]
repository = "https://github.com/dominikkoenitzer/Mochi"
publish = false

[workspace.dependencies]
mochi-core = { path = "crates/mochi-core" }
mochi-client = { path = "crates/mochi-client" }
mochi-render = { path = "crates/mochi-render" }
mochi-hotkey = { path = "crates/mochi-hotkey" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.6", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0"
anyhow = "1.0"
schemars = "1.2"
regex = "1.13"
windows = "0.62"
windows-core = "0.62"
notify = "8"
tracing-appender = "0.2"
embed-manifest = "1.5"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
